import type { ProfileTemplate } from './types';

export const PROFILE_TEMPLATES: ProfileTemplate[] = [
  {
    id: 'musician',
    label: 'Musician',
    description: 'Dark vibes with neon accents',
    icon: 'Music',
    theme: {
      base: 'neon-night',
      colorMode: 'preset',
      preset: 'dusk',
      buttonStyle: 'pill',
      fontPair: 'condensed',
      animation: 'slide-up',
      socialStyle: 'circle',
    },
  },
  {
    id: 'developer',
    label: 'Developer',
    description: 'Clean and professional dark mode',
    icon: 'Code',
    theme: {
      base: 'dark-pro',
      colorMode: 'preset',
      preset: 'midnight',
      buttonStyle: 'outline-sharp',
      fontPair: 'mono-serif',
      animation: 'fade',
      socialStyle: 'icon-only',
    },
  },
  {
    id: 'freelancer',
    label: 'Freelancer',
    description: 'Minimal and elegant',
    icon: 'Briefcase',
    theme: {
      base: 'minimal',
      colorMode: 'preset',
      preset: 'ink',
      buttonStyle: 'filled',
      fontPair: 'geometric',
      animation: 'fade',
      socialStyle: 'pill-label',
    },
  },
  {
    id: 'coach',
    label: 'Coach',
    description: 'Warm and approachable',
    icon: 'Heart',
    theme: {
      base: 'soft-warm',
      colorMode: 'preset',
      preset: 'coral',
      buttonStyle: 'soft',
      fontPair: 'humanist',
      animation: 'scale',
      socialStyle: 'circle-outline',
    },
  },
  {
    id: 'podcaster',
    label: 'Podcaster',
    description: 'Bold typography that pops',
    icon: 'Mic',
    theme: {
      base: 'bold-type',
      colorMode: 'preset',
      preset: 'charcoal',
      buttonStyle: 'filled',
      fontPair: 'editorial',
      animation: 'slide-up',
      socialStyle: 'circle',
    },
  },
  {
    id: 'photographer',
    label: 'Photographer',
    description: 'Frosted glass with moody tones',
    icon: 'Camera',
    theme: {
      base: 'glass',
      colorMode: 'preset',
      preset: 'storm',
      buttonStyle: 'ghost',
      fontPair: 'geometric',
      animation: 'blur-in',
      socialStyle: 'minimal-row',
    },
  },
  {
    id: 'writer',
    label: 'Writer',
    description: 'Classic editorial feel',
    icon: 'BookOpen',
    theme: {
      base: 'paper',
      colorMode: 'preset',
      preset: 'sand',
      buttonStyle: 'underline',
      fontPair: 'slab',
      animation: 'fade',
      socialStyle: 'icon-only',
    },
  },
  {
    id: 'startup',
    label: 'Startup',
    description: 'Modern grid layout',
    icon: 'Rocket',
    theme: {
      base: 'grid',
      colorMode: 'preset',
      preset: 'slate',
      buttonStyle: 'outline-sharp',
      fontPair: 'grotesque',
      animation: 'cascade',
      socialStyle: 'square',
    },
  },
];
