import {
  Twitter, Github, Linkedin, Youtube, Instagram, Music2,
  MessageCircle, Twitch, AtSign, Cloud, Mail, Globe,
  Facebook, Rss, Podcast, Radio,
  Link, ExternalLink, ArrowRight, ArrowUpRight, Star,
  Heart, Bookmark, Share2, ThumbsUp, ThumbsDown,
  Plus, Minus, Check, X, Info, HelpCircle,
  AlertTriangle, Ban, Search, Filter, List,
  Play, Pause, SkipForward, Volume2, Camera, Image,
  Video, Music, Headphones, Mic, Film, Clapperboard,
  Tv, MonitorPlay, Cast, Airplay, Disc,
  Building2, Briefcase, DollarSign, CreditCard,
  ShoppingCart, ShoppingBag, Store, Tag, Receipt,
  Wallet, PiggyBank, TrendingUp, BarChart3, PieChart,
  LineChart, Coins, BadgeDollarSign, Banknote, Landmark,
  Handshake, ClipboardList, FileSpreadsheet,
  Code, Terminal, Database, Server, Cpu, Monitor,
  Laptop, Smartphone, Tablet, Wifi, Bluetooth, Signal,
  Satellite, Bot, Bug, GitBranch, GitCommit,
  GitPullRequest, Binary, Braces, Brackets, Code2,
  CloudDownload, CloudUpload, HardDrive, Usb,
  CircuitBoard, QrCode, Scan, Fingerprint,
  Palette, Brush, PenTool, Pencil, Scissors, Layers,
  Layout, Grid3x3, Figma, Frame, Shapes, Diamond,
  Gem, Sparkles, Wand2, Paintbrush, Eraser, Ruler,
  Pipette, Blend, Crop, Move, Type, Italic,
  BookOpen, GraduationCap, Library, FileText,
  Newspaper, ScrollText, Award, Trophy, Medal, Target,
  Brain, Lightbulb, Lamp, Microscope, FlaskConical,
  Atom, Dna, Beaker, Calculator, NotebookPen,
  HeartPulse, Activity, Dumbbell, Bike, PersonStanding,
  Baby, Apple, Coffee, UtensilsCrossed, Beer, Wine,
  Salad, Leaf, TreePine, Flower2, Mountain, Waves,
  Sun, Moon, CloudRain, Snowflake, Umbrella, Wind,
  Rainbow, Flame, Zap, Droplets, Sprout,
  MapPin, Navigation, Compass, Map, Globe2, Plane,
  Car, TrainFront, Ship, Anchor, Bus, Truck,
  Fuel, Tent, MountainSnow, Palmtree, Sunrise, Sunset,
  Luggage, Ticket, Hotel,
  MessageSquare, MessagesSquare, Send, Inbox, MailOpen,
  Hash, Phone, PhoneCall, Voicemail,
  Megaphone, Bell, BellRing, Siren, Speech,
  Gamepad2, Joystick, Dice1, Dice3, Dice5, Puzzle,
  Crown, Sword, Shield, Ghost, Skull,
  Crosshair, Swords, Flag,
  Home, Key, Lock, Unlock, Settings, Wrench, Hammer,
  Rocket, Gift, Cake, PartyPopper, Sparkle,
  HandMetal, HandHeart, Dog, Cat, Bird, Fish,
  Rabbit, PawPrint, Eye, Glasses, Clock, Timer,
  Calendar, AlarmClock, Hourglass, Battery, Power,
  Download, Upload, Save, Folder, File, Archive,
  Trash2, Recycle, Infinity, Asterisk,
} from 'lucide-react';
import type { FC } from 'react';

type IconProps = { className?: string };

/** Map from kebab-case icon name → Lucide component */
const ICON_MAP: Record<string, FC<IconProps>> = {
  // Social
  'twitter': Twitter, 'github': Github, 'linkedin': Linkedin, 'youtube': Youtube,
  'instagram': Instagram, 'music-2': Music2, 'message-circle': MessageCircle,
  'twitch': Twitch, 'at-sign': AtSign, 'cloud': Cloud, 'mail': Mail, 'globe': Globe,
  'facebook': Facebook, 'rss': Rss, 'podcast': Podcast, 'radio': Radio,
  // General
  'link': Link, 'external-link': ExternalLink, 'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight, 'star': Star, 'heart': Heart, 'bookmark': Bookmark,
  'share-2': Share2, 'thumbs-up': ThumbsUp, 'thumbs-down': ThumbsDown,
  'plus': Plus, 'minus': Minus, 'check': Check, 'x': X, 'info': Info,
  'help-circle': HelpCircle, 'alert-triangle': AlertTriangle, 'ban': Ban,
  'search': Search, 'filter': Filter, 'list': List,
  // Media
  'play': Play, 'pause': Pause, 'skip-forward': SkipForward, 'volume-2': Volume2,
  'camera': Camera, 'image': Image, 'video': Video, 'music': Music,
  'headphones': Headphones, 'mic': Mic, 'film': Film, 'clapperboard': Clapperboard,
  'tv': Tv, 'monitor-play': MonitorPlay, 'cast': Cast, 'airplay': Airplay, 'disc': Disc,
  // Business
  'building-2': Building2, 'briefcase': Briefcase, 'dollar-sign': DollarSign,
  'credit-card': CreditCard, 'shopping-cart': ShoppingCart, 'shopping-bag': ShoppingBag,
  'store': Store, 'tag': Tag, 'receipt': Receipt, 'wallet': Wallet,
  'piggy-bank': PiggyBank, 'trending-up': TrendingUp, 'bar-chart-3': BarChart3,
  'pie-chart': PieChart, 'line-chart': LineChart, 'coins': Coins,
  'badge-dollar-sign': BadgeDollarSign, 'banknote': Banknote, 'landmark': Landmark,
  'handshake': Handshake, 'clipboard-list': ClipboardList, 'file-spreadsheet': FileSpreadsheet,
  // Tech
  'code': Code, 'terminal': Terminal, 'database': Database, 'server': Server,
  'cpu': Cpu, 'monitor': Monitor, 'laptop': Laptop, 'smartphone': Smartphone,
  'tablet': Tablet, 'wifi': Wifi, 'bluetooth': Bluetooth, 'signal': Signal,
  'satellite': Satellite, 'bot': Bot, 'bug': Bug, 'git-branch': GitBranch,
  'git-commit': GitCommit, 'git-pull-request': GitPullRequest, 'binary': Binary,
  'braces': Braces, 'brackets': Brackets, 'code-2': Code2,
  'cloud-download': CloudDownload, 'cloud-upload': CloudUpload,
  'hard-drive': HardDrive, 'usb': Usb,
  'circuit-board': CircuitBoard, 'qr-code': QrCode, 'scan': Scan, 'fingerprint': Fingerprint,
  // Creative
  'palette': Palette, 'brush': Brush, 'pen-tool': PenTool, 'pencil': Pencil,
  'scissors': Scissors, 'layers': Layers, 'layout': Layout, 'grid-3x3': Grid3x3,
  'figma': Figma, 'frame': Frame, 'shapes': Shapes, 'diamond': Diamond,
  'gem': Gem, 'sparkles': Sparkles, 'wand-2': Wand2, 'paintbrush': Paintbrush,
  'eraser': Eraser, 'ruler': Ruler, 'pipette': Pipette, 'blend': Blend, 'crop': Crop,
  'move': Move, 'type': Type, 'italic': Italic,
  // Education
  'book-open': BookOpen, 'graduation-cap': GraduationCap, 'library': Library,
  'file-text': FileText, 'newspaper': Newspaper, 'scroll-text': ScrollText,
  'award': Award, 'trophy': Trophy, 'medal': Medal, 'target': Target,
  'brain': Brain, 'lightbulb': Lightbulb, 'lamp': Lamp, 'microscope': Microscope,
  'flask-conical': FlaskConical, 'atom': Atom, 'dna': Dna, 'beaker': Beaker, 'calculator': Calculator, 'notebook-pen': NotebookPen,
  // Lifestyle
  'heart-pulse': HeartPulse, 'activity': Activity, 'dumbbell': Dumbbell, 'bike': Bike,
  'person-standing': PersonStanding, 'baby': Baby, 'apple': Apple, 'coffee': Coffee,
  'utensils-crossed': UtensilsCrossed, 'beer': Beer, 'wine': Wine, 'salad': Salad,
  'leaf': Leaf, 'tree-pine': TreePine, 'flower-2': Flower2, 'mountain': Mountain,
  'waves': Waves, 'sun': Sun, 'moon': Moon, 'cloud-rain': CloudRain,
  'snowflake': Snowflake, 'umbrella': Umbrella, 'wind': Wind, 'rainbow': Rainbow,
  'flame': Flame, 'zap': Zap, 'droplets': Droplets, 'sprout': Sprout,
  // Travel
  'map-pin': MapPin, 'navigation': Navigation, 'compass': Compass, 'map': Map,
  'globe-2': Globe2, 'plane': Plane, 'car': Car, 'train-front': TrainFront,
  'ship': Ship, 'anchor': Anchor, 'bus': Bus, 'truck': Truck,
  'fuel': Fuel, 'tent': Tent, 'mountain-snow': MountainSnow, 'palm-tree': Palmtree,
  'sunrise': Sunrise, 'sunset': Sunset, 'luggage': Luggage, 'ticket': Ticket, 'hotel': Hotel,
  // Communication
  'message-square': MessageSquare, 'messages-square': MessagesSquare, 'send': Send,
  'inbox': Inbox, 'mail-open': MailOpen, 'hash': Hash, 'phone': Phone,
  'phone-call': PhoneCall, 'voicemail': Voicemail,
  'megaphone': Megaphone, 'bell': Bell, 'bell-ring': BellRing, 'siren': Siren, 'speech': Speech,
  // Gaming
  'gamepad-2': Gamepad2, 'joystick': Joystick, 'dice-1': Dice1, 'dice-3': Dice3,
  'dice-5': Dice5, 'puzzle': Puzzle, 'crown': Crown, 'sword': Sword,
  'shield': Shield, 'ghost': Ghost, 'skull': Skull, 'crosshair': Crosshair,
  'swords': Swords, 'flag': Flag,
  // Misc
  'home': Home, 'key': Key, 'lock': Lock, 'unlock': Unlock, 'settings': Settings,
  'wrench': Wrench, 'hammer': Hammer, 'rocket': Rocket, 'gift': Gift, 'cake': Cake,
  'party-popper': PartyPopper, 'sparkle': Sparkle,
  'hand-metal': HandMetal, 'hand-heart': HandHeart,
  'dog': Dog, 'cat': Cat, 'bird': Bird, 'fish': Fish, 'rabbit': Rabbit,
  'paw-print': PawPrint, 'eye': Eye, 'glasses': Glasses, 'clock': Clock,
  'timer': Timer, 'calendar': Calendar, 'alarm-clock': AlarmClock,
  'hourglass': Hourglass, 'battery': Battery, 'power': Power,
  'download': Download, 'upload': Upload, 'save': Save, 'folder': Folder,
  'file': File, 'archive': Archive, 'trash-2': Trash2, 'recycle': Recycle,
  'infinity': Infinity, 'asterisk': Asterisk,
};

export function getLinkIcon(name: string): FC<IconProps> | null {
  return ICON_MAP[name] ?? null;
}

export { ICON_MAP as linkIconMap };
